export enum flightSearchTypes {
  DAYS_TO_DEPARTURE_SEARCH = "DAYS_TO_DEPARTURE_SEARCH" ,
  DEPARTURE_TIME_SEARCH = "DEPARTURE_TIME_SEARCH",
  ORIGIN_DESTINATION_SEARCH = "ORIGIN_DESTINATION_SEARCH"
}
